# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotedby', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=45)),
                ('u_name', models.CharField(max_length=45)),
                ('e_mail', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pw', models.CharField(max_length=45)),
                ('dob', models.DateField()),
            ],
            managers=[
                ('happiness', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='quotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_created', to='happiness.User'),
        ),
        migrations.AddField(
            model_name='addtolist',
            name='quotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_adds', to='happiness.Quotes'),
        ),
        migrations.AddField(
            model_name='addtolist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_adds', to='happiness.User'),
        ),
    ]
